### ISSUE TITLE
doesn't support initWithCoder:

### ISSUE THREAD

**Issue by pronebird** [griffin-stewie/CSNPlaceholderTextView#2]
Doesn't work if instantiated from Storyboard. Would you mind adding initWithCoder: initializer? 

Thanks.

**Comment by griffin-stewie** [comment]
Thank you @pronebird .

I've never used it from Storyboard and XIB.
I'm going to fix this issue soon.

**Comment by griffin-stewie** [comment]
Hi, @pronebird .
I fixed this issue.
Does this work for you?

**Comment by pronebird** [comment]
Hey, I think I missed your reply. Can't test your class at the moment, but looking at change set it seems legit.
